name: 'Builds container image with cache'
description: 'Builds a Docker container image using a local build cache.'

inputs:
  context:
    description: 'Build context path (default: .)'
    required: false
    type: string
    default: .
  file:
    description: Containerfile name (e.g. Dockerfile,Containerfile,...)
    required: false
    type: string
    default: Dockerfile
  tags:
    description: Comma-separated list of tags for the image (e.g., my-image:latest,my-image:v1)
    type: string
    required: true
  push:
    description: 'Whether to push the image to the registry (default: false)'
    type: boolean
    required: false
    default: false
  load:
    description: 'Whether to load the image into the Docker daemon (default: false)'
    type: boolean
    required: false
    default: false
  registries:
    description: 'JSON list of registries. If empty, defaults to GHCR.io.'
    required: false
    type: string
    default: ''

runs:
  using: "composite"
  steps:
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        # Invalidate the cache if the Dockerfile changes
        key: ${{ runner.os }}-buildx-${{ hashFiles(inputs.file) }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to registries (Default or Custom)
      if: ${{ inputs.push == 'true' }}
      shell: bash
      env:
        # Map inputs and context to environment variables
        INPUT_REGISTRIES: ${{ inputs.registries }}
        DEFAULT_REGISTRY: ghcr.io
        DEFAULT_USER: ${{ github.actor }}
        DEFAULT_PASS: ${{ github.token }}
      run: |
        # 1. Check if the user provided custom registries
        if [[ -n "$INPUT_REGISTRIES" ]] && [[ "$INPUT_REGISTRIES" != "[]" ]]; then
          echo "Custom registries detected. Parsing JSON input..."

          echo "$INPUT_REGISTRIES" | jq -c '.[]' | while read -r item; do
            REGISTRY=$(echo "$item" | jq -r '.registry')
            USERNAME=$(echo "$item" | jq -r '.username')
            PASSWORD=$(echo "$item" | jq -r '.password')

            echo "Logging into $REGISTRY as $USERNAME..."
            echo "::add-mask::$PASSWORD"
            echo "$PASSWORD" | docker login "$REGISTRY" -u "$USERNAME" --password-stdin
          done

        # 2. If input is empty, use the requested Defaults
        else
          echo "No custom registries provided. Defaulting to ghcr.io..."

          echo "Logging into $DEFAULT_REGISTRY as $DEFAULT_USER..."
          echo "::add-mask::$DEFAULT_PASS"
          echo "$DEFAULT_PASS" | docker login "$DEFAULT_REGISTRY" -u "$DEFAULT_USER" --password-stdin
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{inputs.context }}/${{ inputs.file }}
        tags: ${{ inputs.tags }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        # Use local caching for Docker layers
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move new cache to primary location
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      shell: bash
