name: 'Builds container image with cache'
description: 'Builds a Docker container image using a local build cache.'

inputs:
  context:
    description: 'Build context path (default: .)'
    required: false
    type: string
    default: .
  file:
    description: Containerfile name (e.g. Dockerfile,Containerfile,...)
    required: false
    type: string
    default: Dockerfile
  tags:
    description: Comma-separated list of tags for the image (e.g., my-image:latest,my-image:v1)
    type: string
    required: true
  push:
    description: 'Whether to push the image to the registry (default: false)'
    type: boolean
    required: false
    default: false
  load:
    description: 'Whether to load the image into the Docker daemon (default: false)'
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        # Invalidate the cache if the Dockerfile changes
        key: ${{ runner.os }}-buildx-${{ hashFiles(inputs.file) }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{inputs.context }}/${{ inputs.file }}
        tags: ${{ inputs.tags }}
        push: ${{ inputs.push }}
        load: ${{ inputs.load }}
        # Use local caching for Docker layers
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

    - name: Move new cache to primary location
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      shell: bash
