name: Check for broken links
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"
jobs:
  linkChecker:
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}
    container:
      image: ghcr.io/bl4ko/ci-tools:latest@sha256:ff17bf7d70d87ef9b4b57c96de5f809cc4894f74bb3f5bc598a62190c49ca688
    steps:
      - name: Fix composite action paths in container
        run: |
          mkdir -p /home/runner
          ln -s /__w /home/runner/work

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          failIfEmpty: false

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # v6
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
          token: ${{ steps.app-token.outputs.token }}
