name: OSV-Scanner PR Scan
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
      upload-sarif:
        required: false
        type: boolean
        default: true
      scan-args:
        required: false
        type: string
        description: "Arguments to osv-scanner, separated by new line"
        default: |-
          --recursive
          ./

permissions:
  # Required to upload SARIF file to CodeQL.
  actions: read
  # Require writing security events to upload SARIF file to security tab
  security-events: write
  # Only need to read contents
  contents: read

jobs:
  scan-pr:
    runs-on: ${{ inputs.runs-on }}
    container:
      image: ghcr.io/bl4ko/ci-tools:latest@sha256:faaed37746be85bf7ea3e53e02539aca7f5901f9e1c8ec6a4415d1ea8d96facc
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run OSV-Scanner
        id: scanner
        env:
          SCAN_ARGS: ${{ inputs.scan-args }}
          UPLOAD_SARIF: ${{ inputs.upload-sarif }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          ARGS=$(echo "$SCAN_ARGS" | tr '\n' ' ')

          if [ "$UPLOAD_SARIF" = "true" ]; then
            echo "Running osv-scanner with SARIF output..."
            osv-scanner $ARGS --format sarif --output results.sarif
          else
            echo "Running osv-scanner..."
            osv-scanner $ARGS
          fi
        continue-on-error: ${{ inputs.upload-sarif }}

      - name: Upload SARIF file
        if: inputs.upload-sarif == true
        uses: github/codeql-action/upload-sarif@b1bff81932f5cdfc8695c7752dcee935dcd061c8 # v4
        with:
          sarif_file: results.sarif
          category: osv-scanner

      - name: Check for failures
        if: inputs.upload-sarif == true && steps.scanner.outcome == 'failure'
        run: |
          echo "OSV-Scanner found vulnerabilities."
          exit 1
