name: Spellcheck Action
permissions:
  contents: read
on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: "ubuntu-latest"
      container-image:
        required: false
        type: string
        default: "node:lts-bookworm-slim"
jobs:
  spellcheck:
    runs-on: ${{ inputs.runs-on }}
    container:
      image: ${{ inputs.container-image }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: streetsidesoftware/cspell-action@de2a73e963e7443969755b648a1008f77033c5b2 # v8
